"""modify table order and add user table

Revision ID: 9473a357262e
Revises: 3ef42569711a
Create Date: 2025-06-23 15:52:19.014276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9473a357262e'
down_revision: Union[str, Sequence[str], None] = '3ef42569711a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.add_column('order', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('name', sa.String(length=50), nullable=True))
    op.alter_column('order', 'order_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_order_order_id'), table_name='order')
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_unique_constraint(None, 'order', ['order_id'])
    op.drop_column('order', 'member_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('member_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.create_index(op.f('ix_order_order_id'), 'order', ['order_id'], unique=False)
    op.alter_column('order', 'order_id',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('order', 'name')
    op.drop_column('order', 'id')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
