"""modify table order and add type & material enum column

Revision ID: d24b6d4e0188
Revises: 9a724419def3
Create Date: 2025-06-23 21:58:12.122457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24b6d4e0188'
down_revision: Union[str, Sequence[str], None] = '9a724419def3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('type', sa.Enum('sepatu', 'tas', 'topi', name='typeenum'), nullable=False))
    op.add_column('order', sa.Column('material', sa.Enum('kulit', 'suede', 'kanvas', name='materialenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'material')
    op.drop_column('order', 'type')
    # ### end Alembic commands ###
