"""initial migration

Revision ID: e07139cb6ab3
Revises: d5b2925c1353
Create Date: 2025-07-20 21:53:57.325785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e07139cb6ab3'
down_revision: Union[str, Sequence[str], None] = 'd5b2925c1353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('item_name', sa.String(length=50), nullable=True))
    op.add_column('order', sa.Column('cust_name', sa.String(length=50), nullable=True))
    op.add_column('order', sa.Column('cust_address', sa.String(length=100), nullable=True))
    op.alter_column('order', 'order_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('order', 'status',
               existing_type=mysql.ENUM('CP', 'CL', 'IP', 'U', 'S', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False)
    op.drop_column('order', 'name')
    op.drop_column('order', 'material')
    op.drop_column('order', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('type', mysql.ENUM('SH', 'TS', 'TP', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True))
    op.add_column('order', sa.Column('material', mysql.ENUM('KL', 'SD', 'KV', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True))
    op.add_column('order', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('order', 'status',
               existing_type=mysql.ENUM('CP', 'CL', 'IP', 'U', 'S', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=True)
    op.alter_column('order', 'order_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_column('order', 'cust_address')
    op.drop_column('order', 'cust_name')
    op.drop_column('order', 'item_name')
    # ### end Alembic commands ###
