"""initial migration

Revision ID: f3ad0e43a9dc
Revises: e07139cb6ab3
Create Date: 2025-07-20 21:56:47.893616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ad0e43a9dc'
down_revision: Union[str, Sequence[str], None] = 'e07139cb6ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('notes', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'notes')
    # ### end Alembic commands ###
